name: "SHFZ setup"
description: "This action for setup shfz."
inputs:
  version:
    description: "shfz version"
    required: true
    default: "0.0.2"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - name: setup shfz
      run: |
        wget https://github.com/shfz/shfz/releases/download/v${{ inputs.version }}/shfz_${{ inputs.version }}_linux_amd64.tar.gz
        tar -zxvf shfz_${{ inputs.version }}_linux_amd64.tar.gz
        sudo mv shfz /usr/local/bin/
        sudo chmod +x /usr/local/bin/shfz
        shfz --help
      shell: bash
    - name: run shfz server
      run: shfz server &
      shell: bash
